In [4]:
from pathlib import Path

print(Path.cwd())                      # should end with ...\corpus_builder\notebooks

ROOT = Path.cwd().parent               # go up one level: the project folder
RAW = ROOT / "data" / "raw"

for f in RAW.iterdir():                # list the files you put there
    print(f.name, round(f.stat().st_size / 1e6, 1), "MB")

C:\Users\Lenovo\Desktop\data science\NLP\corpus_builder\notebooks
raw_analyst_ratings.csv 327.9 MB
raw_partner_headlines.csv 400.7 MB

In [5]:
import pandas as pd
sample = pd.read_csv(RAW / "raw_analyst_ratings.csv", nrows=5)
sample

,Unnamed: 0,headline,url,publisher,date,stock
0,0,Stocks That Hit 52-Week Highs On Friday,https://www.benzinga.com/news/20/06/16190091/s...,Benzinga Insights,2020-06-05 10:30:54-04:00,A
1,1,Stocks That Hit 52-Week Highs On Wednesday,https://www.benzinga.com/news/20/06/16170189/s...,Benzinga Insights,2020-06-03 10:45:20-04:00,A
2,2,71 Biggest Movers From Friday,https://www.benzinga.com/news/20/05/16103463/7...,Lisa Levin,2020-05-26 04:30:07-04:00,A
3,3,46 Stocks Moving In Friday's Mid-Day Session,https://www.benzinga.com/news/20/05/16095921/4...,Lisa Levin,2020-05-22 12:45:06-04:00,A
4,4,B of A Securities Maintains Neutral on Agilent...,https://www.benzinga.com/news/20/05/16095304/b...,Vick Meyer,2020-05-22 11:38:59-04:00,A

In [13]:
df=pd.read_csv(RAW / "raw_analyst_ratings.csv")
df=df.drop(columns=['Unnamed: 0'])
df.head()
#df.describe().applymap(lambda x: f"{x:,.2f}")

,headline,url,publisher,date,stock
0,Stocks That Hit 52-Week Highs On Friday,https://www.benzinga.com/news/20/06/16190091/s...,Benzinga Insights,2020-06-05 10:30:54-04:00,A
1,Stocks That Hit 52-Week Highs On Wednesday,https://www.benzinga.com/news/20/06/16170189/s...,Benzinga Insights,2020-06-03 10:45:20-04:00,A
2,71 Biggest Movers From Friday,https://www.benzinga.com/news/20/05/16103463/7...,Lisa Levin,2020-05-26 04:30:07-04:00,A
3,46 Stocks Moving In Friday's Mid-Day Session,https://www.benzinga.com/news/20/05/16095921/4...,Lisa Levin,2020-05-22 12:45:06-04:00,A
4,B of A Securities Maintains Neutral on Agilent...,https://www.benzinga.com/news/20/05/16095304/b...,Vick Meyer,2020-05-22 11:38:59-04:00,A

In [14]:
#print(df.isnull().sum())
print(df.duplicated().sum())
df=df.drop_duplicates()

1

In [8]:
df['stock'].nunique()
df.tail()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1407327 entries, 0 to 1407327
Data columns (total 5 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   headline   1407327 non-null  object
 1   url        1407327 non-null  object
 2   publisher  1407327 non-null  object
 3   date       1407327 non-null  object
 4   stock      1407327 non-null  object
dtypes: object(5)
memory usage: 64.4+ MB

In [9]:
#(df['publisher']=="Benjamin Lee").sum()
df['publisher'].value_counts()

publisher
Paul Quintaro        228373
Lisa Levin           186978
Benzinga Newsdesk    150484
Charles Gross         96732
Monica Gerson         82380
                      ...
MoneyGeek                 1
muathe                    1
Robert Morris             1
LeftCoastHedgie           1
Jeremie Capron            1
Name: count, Length: 1034, dtype: int64

In [10]:
df['stock'].value_counts()

stock
MRK     3333
MS      3238
NVDA    3146
MU      3142
QQQ     3106
        ...
DWM        1
DWAT       1
DVP        1
DXJS       1
DXJR       1
Name: count, Length: 6204, dtype: int64

In [11]:
print("Earliest Date:", df['date'].min())
print("Latest Date:", df['date'].max())

Earliest Date: 2009-02-14 00:00:00
Latest Date: 2020-06-11 17:12:35-04:00

In [15]:
print(df['url'])

0          https://www.benzinga.com/news/20/06/16190091/s...
1          https://www.benzinga.com/news/20/06/16170189/s...
2          https://www.benzinga.com/news/20/05/16103463/7...
3          https://www.benzinga.com/news/20/05/16095921/4...
4          https://www.benzinga.com/news/20/05/16095304/b...
                                 ...
1407323    https://www.benzinga.com/news/11/08/1888782/to...
1407324    https://www.benzinga.com/news/earnings/11/06/1...
1407325    https://www.benzinga.com/analyst-ratings/analy...
1407326    https://www.benzinga.com/analyst-ratings/price...
1407327    https://www.benzinga.com/news/ipos/11/05/10789...
Name: url, Length: 1407327, dtype: object

In [19]:
import sys
sys.path.insert(0, "../src")
from corpus.load import load_config, load_sources, select_slice

config=load_config("../config.yaml")
config["paths"]["raw_dir"] = "../data/raw"   
df, stats = load_sources(config)
stats

{'analyst_ratings': {'rows_read': 1407328,
  'bad_dates': 0,
  'share_without_time': 0.9602},
 'partner_headlines': {'rows_read': 1845559,
  'bad_dates': 0,
  'share_without_time': 1.0}}

In [20]:
df["ticker"].value_counts().head(40)

ticker
KR      5127
GILD    4974
DISH    4624
EWJ     4526
MDT     4476
HD      4453
MYL     4446
JWN     4432
FDX     4399
FCAU    4334
FCX     4296
WDC     4219
GRPN    4192
AVGO    4149
VMW     4104
TWX     4099
SLV     4012
CSX     4007
BLK     3989
EA      3938
YHOO    3882
TXN     3872
TJX     3817
OXY     3815
KSS     3801
AXP     3783
CI      3762
GMCR    3669
DOW     3645
HAL     3641
REGN    3638
GME     3637
PBR     3634
PANW    3591
LLY     3538
TSN     3533
SLB     3513
STZ     3510
AEO     3491
LEN     3478
Name: count, dtype: int64

In [21]:
df["ts_utc"].min()

Timestamp('1969-12-31 05:00:00+0000', tz='UTC')

In [22]:
df["ts_utc"].max()

Timestamp('2020-06-11 21:12:35+0000', tz='UTC')

In [23]:
df["ts_utc"].dt.year.value_counts().sort_index()     # headlines per year

ts_utc
1969         1
2009     11489
2010     94198
2011    177982
2012    234044
2013    212050
2014    245022
2015    417215
2016    374937
2017    285913
2018    479525
2019    518954
2020    201557
Name: count, dtype: int64

In [24]:
tickers = ["AAPL", "MSFT", "JPM", "XOM", "JNJ"]       # your candidates
sl = select_slice(df, tickers, "2019-01-01", "2020-07-01")
print(len(sl))
sl["ticker"].value_counts()

4008

ticker
JPM     2384
JNJ      663
XOM      488
AAPL     473
Name: count, dtype: int64

In [25]:
interim = Path("../data/interim")            # ../ because the notebook runs from notebooks/
interim.mkdir(parents=True, exist_ok=True)   # creates data/interim if it doesn't exist

sl.to_parquet(interim / "slice.parquet", index=False)
print(len(sl), "rows saved to", interim / "slice.parquet")

4008 rows saved to ..\data\interim\slice.parquet

In [27]:
sl = pd.read_parquet("../data/interim/slice.parquet")
sl.dtypes

headline                    object
ticker                      object
publisher                   object
url                         object
ts_utc         datetime64[ns, UTC]
has_time                      bool
source_file                 object
dtype: object