In [2]:
from pathlib import Path

print(Path.cwd())                      # should end with ...\corpus_builder\notebooks

ROOT = Path.cwd().parent               # go up one level: the project folder
RAW = ROOT / "data" / "raw"

for f in RAW.iterdir():                # list the files you put there
    print(f.name, round(f.stat().st_size / 1e6, 1), "MB")

C:\Users\Lenovo\Desktop\data science\corpus_builder\notebooks
raw_analyst_ratings.csv 327.9 MB
raw_partner_headlines.csv 400.7 MB

In [4]:
import pandas as pd
sample = pd.read_csv(RAW / "raw_analyst_ratings.csv", nrows=5)
sample

,Unnamed: 0,headline,url,publisher,date,stock
0,0,Stocks That Hit 52-Week Highs On Friday,https://www.benzinga.com/news/20/06/16190091/s...,Benzinga Insights,2020-06-05 10:30:54-04:00,A
1,1,Stocks That Hit 52-Week Highs On Wednesday,https://www.benzinga.com/news/20/06/16170189/s...,Benzinga Insights,2020-06-03 10:45:20-04:00,A
2,2,71 Biggest Movers From Friday,https://www.benzinga.com/news/20/05/16103463/7...,Lisa Levin,2020-05-26 04:30:07-04:00,A
3,3,46 Stocks Moving In Friday's Mid-Day Session,https://www.benzinga.com/news/20/05/16095921/4...,Lisa Levin,2020-05-22 12:45:06-04:00,A
4,4,B of A Securities Maintains Neutral on Agilent...,https://www.benzinga.com/news/20/05/16095304/b...,Vick Meyer,2020-05-22 11:38:59-04:00,A

In [16]:
df=pd.read_csv(RAW / "raw_analyst_ratings.csv")
df=df.drop(columns=['Unnamed: 0'])
df.head()
#df.describe().applymap(lambda x: f"{x:,.2f}")

,Unnamed: 0,headline,url,publisher,date,stock
0,0,Stocks That Hit 52-Week Highs On Friday,https://www.benzinga.com/news/20/06/16190091/s...,Benzinga Insights,2020-06-05 10:30:54-04:00,A
1,1,Stocks That Hit 52-Week Highs On Wednesday,https://www.benzinga.com/news/20/06/16170189/s...,Benzinga Insights,2020-06-03 10:45:20-04:00,A
2,2,71 Biggest Movers From Friday,https://www.benzinga.com/news/20/05/16103463/7...,Lisa Levin,2020-05-26 04:30:07-04:00,A
3,3,46 Stocks Moving In Friday's Mid-Day Session,https://www.benzinga.com/news/20/05/16095921/4...,Lisa Levin,2020-05-22 12:45:06-04:00,A
4,4,B of A Securities Maintains Neutral on Agilent...,https://www.benzinga.com/news/20/05/16095304/b...,Vick Meyer,2020-05-22 11:38:59-04:00,A

In [28]:
#print(df.isnull().sum())
print(df.duplicated().sum())
df=df.drop_duplicates()

0

In [35]:
df['stock'].nunique()
df.tail()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1407327 entries, 0 to 1407327
Data columns (total 5 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   headline   1407327 non-null  object
 1   url        1407327 non-null  object
 2   publisher  1407327 non-null  object
 3   date       1407327 non-null  object
 4   stock      1407327 non-null  object
dtypes: object(5)
memory usage: 64.4+ MB

In [33]:
#(df['publisher']=="Benjamin Lee").sum()
df['publisher'].value_counts()

publisher
Paul Quintaro        228373
Lisa Levin           186978
Benzinga Newsdesk    150484
Charles Gross         96732
Monica Gerson         82380
                      ...
MoneyGeek                 1
muathe                    1
Robert Morris             1
LeftCoastHedgie           1
Jeremie Capron            1
Name: count, Length: 1034, dtype: int64

In [34]:
df['stock'].value_counts()

stock
MRK     3333
MS      3238
NVDA    3146
MU      3142
QQQ     3106
        ...
DWM        1
DWAT       1
DVP        1
DXJS       1
DXJR       1
Name: count, Length: 6204, dtype: int64

In [36]:
print("Earliest Date:", df['date'].min())
print("Latest Date:", df['date'].max())

Earliest Date: 2009-02-14 00:00:00
Latest Date: 2020-06-11 17:12:35-04:00

In [37]:
print(df['url'])

0          https://www.benzinga.com/news/20/06/16190091/s...
1          https://www.benzinga.com/news/20/06/16170189/s...
2          https://www.benzinga.com/news/20/05/16103463/7...
3          https://www.benzinga.com/news/20/05/16095921/4...
4          https://www.benzinga.com/news/20/05/16095304/b...
                                 ...
1407323    https://www.benzinga.com/news/11/08/1888782/to...
1407324    https://www.benzinga.com/news/earnings/11/06/1...
1407325    https://www.benzinga.com/analyst-ratings/analy...
1407326    https://www.benzinga.com/analyst-ratings/price...
1407327    https://www.benzinga.com/news/ipos/11/05/10789...
Name: url, Length: 1407327, dtype: object